#!/bin/bash

# Copy files
cp -r completion_scripts $HOME/.completion_scripts
cp -r dotfiles/lib $HOME/.bash_lib
cp dotfiles/.bash_init $HOME
cp .inputrc $HOME

# Add bash_init to bash_profile
cat >> $HOME/bash_profile
\# DO NOT EDIT, GENERATED BY workspace/install.sh 
source .bash_init
^D