#!/bin/bash

# Copy files
cp -r completion_scripts $HOME/.completion_scripts
cp -r dotfiles/lib $HOME/.bash_lib
cp dotfiles/.bash_init $HOME
cp .inputrc $HOME

# Insert into bash_profile
if grep -q "source .bash_init" "$HOME/.bash_profile"; then
  echo ".bash_init already referenced in .bash_profile, ignoring"
else
  # Add bash_init to bash_profile
  echo '### DO NOT EDIT, GENERATED BY workspace/install.sh ###' >> $HOME/.bash_profile
  echo 'source .bash_init' >> $HOME/.bash_profile    
fi

echo "Workspace installed/updated"